model:
  name: "Qwen/Qwen2.5-7B-Instruct" # Can change 3B
  dtype: "fp16"
  attn_implementation: "eager" #"sdpa"
  use_upcasting: true
  load_in_4bit: false
  device: "cuda"

global:
  seed: 42
  strategies: ["Aligned", "Naive"]

paths:
  save_dir: "./results"
  cache_dir: "./.cache/huggingface"

datasets:
  musique:
    enabled: true
    path: "bdsaglam/musique"
    subset: "answerable"
    split: "validation"
    num_samples: 2000
    max_new_tokens: 15
    task_type: "qa"
    compute_attn: true

  samsum:
    enabled: true
    path:  "knkarthick/samsum"
    subset: null
    split: "test"
    num_samples: 1000
    max_new_tokens: 128
    task_type: "summarization"
    compute_attn: true

  ruler:
    enabled: false
    path: "rbiswasfc/ruler"
    subset: "niah_multikey_1_4k" # niah_multikey_1_8k
    split: "validation"
    num_samples: 500
    max_new_tokens: 10
    task_type: "qa"
    compute_attn: false
